// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdfxqwkuirbizwqrvtsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkZnhxd2t1aXJiaXp3cXJ2dHNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxOTc1MTYsImV4cCI6MjA2MDc3MzUxNn0.9frq2dWizIur8ljMxsInTaaqwLH3sMYCJ_Ws-3_LqSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);